export { default as About } from './About/About'
export { default as Home } from './Home/Home'
export { default as Projects } from './Projects/Projects'
export { default as Contact } from './Contact/Contact'
export { default as Error } from './Error/Error'